### ISSUE TITLE
Configure Travis CI for build automation

### ISSUE THREAD

**Issue by estevaoam** [LoveMondays/devise-vero#1]
Hey guys, great work on this release!
I want to suggest you guys to use Travis to build and test this gem across different ruby versions: https://travis-ci.org/getting_started

:metal:

**Comment by shaneog** [comment]
Thanks @estevaoam. We're using Travis already to test on several Ruby versions (see `.travis.yml`), but I want to set it up to test across multiple Rails versions too. 
You can see the test results here: https://travis-ci.org/LoveMondays/devise-vero

**Comment by estevaoam** [comment]
Shame on me, sorry, didn't notice it. :flushed:

Good idea about the Rails versions. :+1:
Took a look on the code, looks amazing, great job! :tada: :
